name: Challenge
on: push
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
    - name: print date
      run: date
  job2:
    name: job2
    runs-on: windows-latest
    steps:
    - name: print date
      run: date
  job3:
    name: job3
    runs-on: macos-latest
    steps:
    - name: print date
      run: date
  job4:
    name: job4
    needs: [job1,job2,job3]
    runs-on: ubuntu-20.04
    steps:
    - name: print date
      run: date